name: quant_trading
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - pyarrow
  - fastparquet
  - pip
  - pip:
    - yfinance
    - ta
    - gymnasium
    - stable-baselines3[extra]